
services:
  es01:
    build:
      context: .
    volumes:
      - blackeveryday:/usr/share/elasticsearch/data
      - ./synonym.txt:/usr/share/elasticsearch/config/synonyms/synonym.txt
      - ./stop_words.txt:/usr/share/elasticsearch/config/stop_words.txt
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms8g -Xmx8g
    networks:
      - elastic
    ports:
      - 9200:9200
    restart: always

  kib01:
    image: docker.elastic.co/kibana/kibana:8.9.0
    environment:
      - "ELASTICSEARCH_HOSTS=http://es01:9200"
    ports:
      - "5601:5601"
    networks:
      - elastic
    container_name: kib01
    restart: always
    depends_on:
      - es01

  log01:
    image: docker.elastic.co/logstash/logstash:8.9.0
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./postgresql-42.6.0.jar:/usr/share/logstash/postgres_driver/postgresql-42.6.0.jar
    networks:
      - elastic
    container_name: log01
    restart: always
    depends_on:
      - es01

networks:
  elastic:
    driver: bridge

volumes:
  blackeveryday:

